#!/usr/bin/env python3
"""Backlog item 19: the running list of posts that beat the median reach.

What is worth copying from a good post is its structure (format, length, how
the hook opens), not its topic: the topic is gone tomorrow. So every post in
the latest metrics snapshot is tagged with its shape, the ones above median
reach are listed with that shape, and the per-shape medians are written next
to them so a pattern is visible without being claimed.

Reads metrics/post-metrics.jsonl, writes metrics/winners.md. Run daily by
stocklearneasy-ig-improve.sh right after the snapshot. At a reach of a few
accounts per post this is a record, not evidence: item 86 still applies, and
nothing here should be called a result until a shape has 10 posts.
"""
import json
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
METRICS = ROOT / "metrics" / "post-metrics.jsonl"
OUT = ROOT / "metrics" / "winners.md"
MIN_PER_SHAPE = 10  # item 86


def latest_snapshot():
    """The most recent reading of every post, keyed by slot."""
    latest = {}
    for line in METRICS.read_text(encoding="utf-8").splitlines():
        row = json.loads(line)
        if row.get("kind") != "post":
            continue
        prev = latest.get(row["slot"])
        if prev is None or row["date"] >= prev["date"]:
            latest[row["slot"]] = row
    return latest


def shape(slot):
    """Format, origin and opening of a published post, read from its folder."""
    d = ROOT / "published" / slot
    if not d.is_dir():
        return None
    reel = json.loads((d / "reel.json").read_text()) if (d / "reel.json").exists() else None
    src = json.loads((d / "source.json").read_text()) if (d / "source.json").exists() else None
    caption = (d / "caption.txt").read_text(encoding="utf-8") if (d / "caption.txt").exists() else ""
    hook = caption.strip().splitlines()[0] if caption.strip() else ""
    if reel and not src:
        kind = "episode reel"  # hand-built lesson reel, queued by queue_episode.py
    elif reel and reel.get("video_url"):
        kind = "news reel"
    else:
        kind = "carousel"
    return {
        "kind": kind,
        "category": (src or {}).get("category") or (reel or {}).get("episode", "?"),
        "seconds": (reel or {}).get("duration_seconds"),
        "question_hook": hook.endswith("?"),
        "hook": hook,
    }


def main():
    posts = []
    for slot, row in sorted(latest_snapshot().items()):
        s = shape(slot)
        if s:
            posts.append({**row, **s})
    if not posts:
        print("no posts with metrics yet")
        return

    median = statistics.median(p["reach"] for p in posts)
    by_kind = defaultdict(list)
    for p in posts:
        by_kind[p["kind"]].append(p["reach"])

    lines = [
        "# Above-median posts (backlog item 19)",
        "",
        f"Generated by winners.py from the {posts[0]['date'][:10]}..{max(p['date'] for p in posts)} "
        f"snapshots. {len(posts)} posts, median reach {median:g}.",
        "",
        "Copy the structure, never the topic. A shape with fewer than "
        f"{MIN_PER_SHAPE} posts is an anecdote (item 86).",
        "",
        "## Median reach by shape",
        "",
    ]
    for kind, reaches in sorted(by_kind.items(), key=lambda kv: -statistics.median(kv[1])):
        flag = "" if len(reaches) >= MIN_PER_SHAPE else " (too few to conclude)"
        lines.append(f"- {kind}: median {statistics.median(reaches):g} over {len(reaches)} posts{flag}")
    lines += ["", "## Above the median", ""]
    for p in sorted((p for p in posts if p["reach"] > median), key=lambda p: -p["reach"]):
        secs = f", {p['seconds']:g}s" if p["seconds"] else ""
        q = ", question hook" if p["question_hook"] else ""
        lines.append(
            f"- {p['slot']} reach {p['reach']}, shares {p['shares']}, saves {p['saved']}: "
            f"{p['kind']}{secs}, {p['category']}{q}. \"{p['hook']}\""
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
